
server:
  port: 8082

bird:
  eventbus:
    kafka:
      host: 127.0.0.1:9092
      provider:
        defaultTopic: bird-kafka-default-topic
        retries: 5
        batchSize: 16384
        lingerms: 3
        bufferMemory: 33554432
#      listener:
#        base-packages: com.bird.eventbus.sample
#        group-id: bird-event-sample-group