server:
  port: 8080

spring:
  application:
    name: bird-trace-client-sample
  datasource:
    url: jdbc:mysql://localhost:3306/demo-zero?useSSL=false&serverTimezone=UTC
    username: root
    password: bird123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
bird:
  trace:
    client:
      sql-types: select,insert,update,delete
